package runner

import (
	"context"
	"errors"
	"fmt"

	"github.com/sanjbh/jokester/internal/agent"
	"github.com/tmc/langchaingo/llms"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

type Runner struct {
	tracer trace.Tracer
}

type Result struct {
	FinalOutput string
}

func New(tracer trace.Tracer) *Runner {
	return &Runner{
		tracer: tracer,
	}
}

func (r *Runner) Run(ctx context.Context, a *agent.Agent, prompt string) (*Result, error) {
	ctx, span := r.tracer.Start(ctx, "runner.run")
	defer span.End()

	span.SetAttributes(
		attribute.String("agent.name", a.Name),
		attribute.String("agent.model", a.Model),
		attribute.Int("prompt.length", len(prompt)),
	)

	msgs := []llms.MessageContent{
		{
			Role: llms.ChatMessageTypeSystem,
			Parts: []llms.ContentPart{
				llms.TextContent{
					Text: a.Instructions,
				},
			},
		},
		{
			Role: llms.ChatMessageTypeHuman,
			Parts: []llms.ContentPart{
				llms.TextContent{
					Text: prompt,
				},
			},
		},
	}

	response, err := a.GetLLM().GenerateContent(ctx, msgs)
	if err != nil {
		span.RecordError(err)
		return nil, fmt.Errorf("failed to generate response: %w", err)
	}

	if len(response.Choices) == 0 {
		err := errors.New("no response was generated by LLM")
		span.RecordError(err)
		return nil, err
	}

	text := response.Choices[0].Content

	span.SetAttributes(
		attribute.Int("output.length", len(text)),
	)

	return &Result{
		FinalOutput: text,
	}, nil

}
